---
- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  environment:
    ZDOTDIR: "{{ zsh_zdotdir }}"
    XDG_CONFIG_HOME: "{{ zsh_xdg_config_home }}"
    XDG_DATA_HOME: "{{ zsh_xdg_data_home }}"
