---
# converge.yml is the playbook file that contains the call for your role.
# Molecule will invoke this playbook with ansible-playbook and run it against an instance created by the driver.
# See: https://molecule.readthedocs.io/en/latest/getting-started/#the-scenario-layout
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      become: true
      become_user: root

    - name: Debug; print zsh_user.
      ansible.builtin.debug:
        msg: "Installing/configuring ZSH for user with username \"{{ zsh_user }}\""

    - name: Debug; print zsh_xdg_config_home.
      ansible.builtin.debug:
        msg: "Installing/configuring ZSH with XDG_CONFIG_HOME={{ zsh_xdg_config_home }}"

    - name: Debug; print zsh_xdg_data_home.
      ansible.builtin.debug:
        msg: "Installing/configuring ZSH with XDG_DATA_HOME={{ zsh_xdg_data_home }}"

    - name: Debug; print zsh_zdotdir.
      ansible.builtin.debug:
        msg: "Installing/configuring ZSH with ZDOTDIR={{ zsh_zdotdir }}"

    - name: Ensure zsh_user group exists.
      ansible.builtin.group:
        name: "{{ zsh_user }}"
      become: true
      become_user: root

    - name: Ensure zsh_user user exists.
      ansible.builtin.user:
        name: "{{ zsh_user }}"
        append: true
        group: "{{ zsh_user }}"
        groups: "{{ zsh_user }}"
      become: true
      become_user: root

  roles:
    - role: librick.zsh
